### ISSUE TITLE
epic: CR.LIFE content migration

### ISSUE THREAD

**Issue by bspain** [crossroads-mn/crlife-issues#2]
CR.LIFE wordpress content needs to be migrated.  The 'application' portions of CR.LIFE have already been migrated (Groups/Events/Bible reading), what remains are new versions of the basic info and forms pages:

The new CR.LIFE will be hosted by GoDaddy Wordpress hosting

Current CR.LIFE plugins are bloated, some are locked behind paywalls, and few seem to supply significant value.  Redesign should focus on simplistic layout while minimizing non 'out-of-box' plugin dependencies.

Core functionality pieces:
- Landing page animation style (although this is very non-mobile friendly - any good CSS animators?)
- Buttons which expose additional collapse/expand text
- Sign up forms (form submission targets may vary my ministry)
- Embedded YouTube links
- Embedded 'Out of Print' HTML (this may be getting sources from crossroadschurch.co) (**fyi** section)
- Embedded 'Spotify' playlist (**music** section)
- Embedded 'Google Maps' (**locations**)

Functionality of **Groups**, **Events**, and **Bible** sections are independent apps.

## Tasks
- [ ] Determine template/theme/styling for animation (if required), but need good mobile layout consideration
- [ ] Migrate marquee **Call To Action**
- [ ] Migrate **Kids** section (Buttons, signup forms)
- [ ] Migrate **Message** section (Buttons, embedded YouTube link)
- [ ] Migrate **Baptism** section (Buttons, embedded YouTube links, signup forms)
- [ ] Migrate **Give** section (Buttons, links)
- [ ] Migrate **f-y-i** (will need to establish a workflow with Communications/Danielle around how to migrate weekly Out-of-Print)
- [ ] Migrate **Youth** section (Buttons, links)
- [ ] Migrate **Music* * section (embedded Spotify playlist)
- [ ] Migrate **Serve** section (buttons, forms)
- [ ] Migrate **Locations** section (embedded google maps)
